### ISSUE TITLE
Yocto build issue

### ISSUE THREAD

**Issue by lfdmn** [juangburgos/QUaServer#19]
First thanks for this interesting project!

I've made a quick proof of concept using Qt 5.13 on a Linux desktop. 

My final target platform is NVidia TX2 / Xavier. I use Yocto to build the OS image and I'm now making a recipe for QUaServer.

In `open62541amalgamation.pri`, is there a specific reason why you are testing for `linux-g++`. We use `unix` in our projects. The issue here being that, when building with qmake for an embedded device, we should either test for `b2qt` (commercial name for embedded platform) or `unix`.

So with `linux-g++` build fails and with `unix` the build succeeds.

I can apply a patch at compilation time in the bitbake recipe, but if you'd like to enable support for Qt on embedded devices, Tegra, raspberrypi, imx, etc. This should be changed.

I'm also temped to make a .pro file to create a DLL for this project and make Linux style rpm dependency package to have the library in the SDK distribution. Any comment / feedback on that?

Cheers,
-Damien

**Comment by juangburgos** [comment]
Hi Damien,

I test for `linux-g++` and windows because it is the platforms I use and have not yet considered others, but if you have tested the `unix` flag and it works for you and does not brake linux compilation then feel free to make a PR.

My wish for 2020 is to learn Yocto, so you know more than me in that matter. Feel free to add any non-breaking improvements to support Yocto images.

Regarding making `QUaServer` a shared library, I have not tested it, but since it relies a lot on templates (to instantiate objects and variables among other things), I don't know if it will really bring any compile time speed improvements. You would have to test and see if it really brings any good. In case you decide to do so, please add it as a `qmake` option, something like `CONFIG+=ua_shared` or whatever flag name you would like.

Looking forward to see your contributions and thank you for your interest in this project.
