### ISSUE TITLE
Certificate and Encryption

### ISSUE THREAD

**Issue by embbo** [juangburgos/QUaServer#5]
Hi all, I am new to encryption and certificate .. I builed accroding to tutorials given on this page. but I have some question . 

1. when I used "ca.der.crl" and "ca.crt.der" and try to connect to with Server it connects fine but if  i delted these two files and try tou connect UaExpert with Server .It shows me some warning and I have to Accerpt the server .. and again ot connects ..So my question is what is difference between both cases.
it should not to connect .
![image](https://user-images.githubusercontent.com/35342156/61451457-b4157780-a959-11e9-8d4f-5a81a32f8a4e.png)

**Comment by juangburgos** [comment]
Hi,
Did you already read [this document](https://github.com/juangburgos/QUaServer/blob/master/VALIDATION.md)? Do you understand the concepts in there?

You are getting those red warnings because the client needs to know in advance which servers he can trust. That information is included in the Certificate Authority's certificate and revocation list.

**Comment by embbo** [comment]
yes i did, but my question is why it connects when I check the option ..... Accept the server certificate for this session . (at the end of scree shot).

**Comment by juangburgos** [comment]
It connects because you are explicitly saying that you trust the server. 

So the client app allows you to continue eventhough it does not have an automatic way to verify the trustworthyness of the server, but that is only because you manually chose to trust it.

Have you ever seen these in your browser?

![image](https://user-images.githubusercontent.com/4707341/61461518-20e83c00-a971-11e9-8ccf-7430aab9c059.png)

Is the same thing, the browser is telling you "I have no automatic way to determine that this website is trust worthy, but you can continue if you want"

**Comment by embbo** [comment]
okay , got it , it means it allowed from server side , that it can connect to any client

**Comment by juangburgos** [comment]
No, is the client that has to trust the server. The server allows for any client to connect by default, unless you enable [user/password authentication](https://github.com/juangburgos/QUaServer#users). 

Do not confuse the mechanism that make clients trust servers with the mechanims that make servers trust clients.

**Comment by embbo** [comment]
okay ... let me read it again come to you back thankyou

**Comment by embbo** [comment]
okay, It works fine thank you ...but still i have a question . Can I write these key.der and cer.der in eeprom ? at run time ..

**Comment by juangburgos** [comment]
If you'd like to have those files embedded in your application I suggest to bundle them using [The Qt Resource System](https://doc.qt.io/qt-5/resources.html). This way your app will bundle the files with the executable, but in code you can treat them as regular files.

**Comment by embbo** [comment]
but I mean at he run time? so i can direct upload from node ..

**Comment by juangburgos** [comment]
I mean the server files (`server.crt.der` and `server.key.der`), they need to be loaded once at startup and that's it. There is no need to load them afterwards at run time. So you can use The Qt Resource System for those. 

The client files though (`ca.crt.der`, `ca.der.crl`), those need to be installed manually for every client, there is no automated way to do that.

**Comment by embbo** [comment]
okay , I got it thank you :)

**Comment by embbo** [comment]
but Is it possible , If i want to change the certificate at run time and want to write in EEPROM .

**Comment by juangburgos** [comment]
That I dont know. I dont handle EEPROM. You will have to investigate yourself. Good luck and let me know if you succeed.

**Comment by embbo** [comment]
okay thnakyou , I will :)

**Comment by embbo** [comment]
can I used " -----BEGIN CERTIFICATE-----" and -----BEGIN PRIVATE KEY----- as string instead of Hex  0x2D 0x2D 0x2D  from server.crt and server.key file rspectively
